spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: org.sqlite.JDBC
    url: jdbc:sqlite:./data/app.db
  sql:
    init:
      mode: always
      schema-locations: classpath:schema-sqlite.sql
  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
      database: ${REDIS_DATABASE:0}

mybatis:
  configuration:
    map-underscore-to-camel-case: true
